ranger
alias la="ls -a"
alias n="nvim"
alias games="nixGL steam"
alias c="clear"
alias nixconfig="sudo nvim /etc/nixos/configuration.nix"
alias nswitch="sudo nixos-rebuild switch"
alias ni="nix-env -iA"
alias bashu="source ~/.bashrc"
alias l="ls"
alias la="ls -a"
alias g="python3 ~/g.py"
alias r="ranger"
alias gp="git push origin master"
alias ga="git add."
